version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: hello-world-app-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hello-world-app-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydatabase
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hello-world-app-frontend
    restart: always
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"

volumes:
  postgres_data:
