version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    image: jefrey0/hello-world-frontend:latest
    networks:
      - hello-world-net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=password
    volumes:
      - ./backend:/app
    image: jefrey0/hello-world-backend:latest
    networks:
      - hello-world-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Bind PostgreSQL to host port 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hello-world-net

volumes:
  postgres_data:
    driver: local

networks:
  hello-world-net:
    driver: bridge
