version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    image: jefrey0/hello-world-frontend:latest

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres  # Ensure DB_HOST is set to 'postgres'
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=password
    volumes:
      - ./backend:/app
    image: jefrey0/hello-world-backend:latest

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
