version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - hello-world-net

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - hello-world-net
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres       # Set the DB_HOST to the service name 'postgres'
      - DB_NAME=mydatabase     # Set the DB_NAME
      - DB_USER=user           # Set the DB_USER
      - DB_PASSWORD=password   # Set the DB_PASSWORD

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Changed host port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hello-world-net

volumes:
  postgres_data:
    driver: local

networks:
  hello-world-net:
    driver: bridge
