version: "3.8"

services:
  # Frontend ReactJS application
  frontend:
    image: jefrey0/react-app:latest  
    ports:
      - "3000:3000"  
    depends_on:
      - backend  
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000  

  # Backend Flask application
  backend:
    image: jefrey0/flask-app:latest  
    ports:
      - "5000:5000"  
    depends_on:
      - postgres  
    environment:
      # PostgreSQL connection details
      - DB_HOST=postgres
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=password

  # PostgreSQL Database
  postgres:
    image: postgres:13  
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: user  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: mydatabase  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

# Volumes for persistent storage
volumes:
  postgres_data:
    driver: local
